### PR TITLE
tweaks.json: add 2021093001 'Fix date-stamp blobs (TEMP FIX)'

### PR DESCRIPTION
**Pull request by filbo**
A stopgap fix for the fact that FB no longer notice our pointerout /
mouseout events, apparently insisting on isTrusted.  Thus, the screen
is littered with date stamp blobs.

The crude fix is to fade out such blobs after 5s.  Not shorter, because
this affects a whole class of such blobs, including the list of who
'liked' a post when hovering the blue thumb-with-count, and, I think,
some immediate action undo buttons.

This needs a real fix by SFx either no longer doing the hover thing to
provoke the permalink URL, or figuring out how to convince it we've
moused off.

### CODE REVIEW

**Comment by mjeveritt** [comment]
Presumably this is a nasty side-effect of "mousing" the date to get the permalink still? I think we might have to sacrifice MarkAsRead until a more robust method is found for this, else we're chasing a [fast-]moving target here.

What is the 'isTrusted' function you speak of, and how does it apply to the interaction process[es]?

**Comment by filbo** [comment]
Michael, yes, mousing to get the permalink.

isTrusted is one of the fields of a JS event.  Events which are generated by the system (here, the browser) are isTrusted=true.  Events which are synthetically generated by JS code -- like in SFx's 'unmouse' code which does new PointerEvent('pointerout') -- are isTrusted=false.  JS code cannot change that field.

These mouse events have multiple effects, in the context of the FB post structure:

(1) pointerover => date tooltip pops up
(2) pointerover => permalink href changes from '#' to actual permalink
(3) pointerout => date tooltip goes away

Before whatever FB changed recently, all 3 of those effects would happen.

After their recent change, (1) still happens, but (2) and (3) do not.  This seems to imply that the code which does the href rewriting, and the (different) code which tears down the tooltip, are now both paying attention to isTrusted.  I don't **know** that to be the actual cause; I couldn't find it in their code.  But, that's how it's behaving.

**Comment by mjeveritt** [comment]
Gotcha, sounds entirely plausible, if somewhat unhelpful.

I'm a bit surprised they (FB) are going to this level of effort to obfuscate this particular feature, when there are surely 'bigger fry' for them to frustrate us with. Granted, this is a pretty big visual 'episode' to deal with...

**Comment by filbo** [comment]
Given how haphazardly it reacts to trusted vs untrusted events for the different listeners, I would guess this is due to some sort of framework maintenance.  The person making the change probably has no clue that it has had these effects (probably wouldn't care very much about it if they learned, but that's a separate issue)

**Pull request merged**
