### PR TITLE
post-internal junk nuggets

### PR DESCRIPTION
**Pull request by filbo**
hideable.json: add 2021091801 'Post: Climate Science'
hideable.json: make 2021042301 'Post: Covid Info' slightly less specific / more robust

### CODE REVIEW

**Comment by filbo** [comment]
@mjeverrit -- please test this slightly tweaked version (make sure you've first cleared away your 2021090101 version from both custom_hideables **and** hiddens)

**Comment by mjeveritt** [comment]
> @mjeverrit -- please test this slightly tweaked version (make sure you've first cleared away your 2021090101 version from both custom_hideables **and** hiddens)

slight typo @mjeveritt (double-t, one R) ;)

**Comment by mjeveritt** [comment]
image
with hideables.json deployed as 'custom' (no merge).
image
and 'unblock' preview.

**Comment by mjeveritt** [comment]
or better like this:
image
stupid screenshot shading/etc (Window manager 'features').

**Comment by filbo** [comment]
That's great, thanks!

(Even better would be if you used the tweak from fb.com/3578826682202056 to show floating title, but -- this will do...)

**Comment by mjeveritt** [comment]
> That's great, thanks!
> 
> (Even better would be if you used the tweak from fb.com/3578826682202056 to show floating title, but -- this will do...)

Oh, shoot, I'll see if I can merge that in.

What's the "right" process of undoing custom hidables? do I need to hack my settings again, once the new hideable is available from Matt's host?! :joy:

**Comment by filbo** [comment]
> What's the "right" process of undoing custom hidables? do I need to hack my settings again, once the new hideable is available from Matt's host?!

The simple move is to just clear out the 'Custom Hideables' field.

Problems will ensue if you do this while anything is hidden by an entry from Custom Hideables, with a hider which differs from the hosted list in any regard (well, specifically: id, selector, and parent; name doesn't matter).  Hiding anything (with either the hosted list or custom) adds an entry to your SFx settings 'hiddens { }' structure.  Aside from manual JSON surgery, the only way to remove an item from that structure is to 'unhide' it with Hide/Show; which means that a matching entry must exist in either the hosted list or your Custom Hideables.

This is why I always tell people not to hide things with test hiders.  It is actually OK to do so, but only if you subsequently **unhide** the same things.  And, due to how Hide/Show works, you can only unhide a thing if FB happen to send you an instance of that thing.  e.g. if you hid 'Covid junk' inside a post, you might later be unable to unhide it because you can't find any posts which FB have decided to tack that junk onto.

So it's better not to hide with a test hider.

SPECULATIVE [not tested]: you could probably surgically remove a hider using Hide/Show, by using a specially crafted fake hider.  Items in hiddens{} are keyed only by 'id'.  To get rid of a hider with ID 123456, you could create a fake hider like:

{"hideables":[{"id":123456,"selector":"[role=banner] [role]","name":"fake"}]}

in Custom Hideables.  Turn OFF 'Merge', so the only thing Hide/Show will show you is the fake hider.  Then go into Hide/Show, turn on [x] Show Hidden, then hide and unhide the top bar.  I think this will remove the entry of that ID from hiddens{}.

(Tested a bit.  My hiddens{} has many entries for old hiders which will never be seen again.  I used this method to erase id:100, 'Left Col: Friend Lists', which is useless since it only applies to old layout.  It worked.)

**Comment by mjeveritt** [comment]
Yeah, what I did last time, to get -back- the combined hideables, back to Server-side or your custom update (ie. the 'after' side of the diff) .. was to Export settings to the Textbox in SFx options, manually edit the hideables JSON, then Import from the textbox.
It seemed to work fine - neat hack, if you should need it, or need to walk someone else through it :wink:

**Pull request merged**
