### PR TITLE
- hideable.json: "Right Col: Local Products in Marketplace"

### PR DESCRIPTION
**Pull request by filbo**
This is completely untested, working from a screenshot of 'inspect element' sent by a user.

I expect it'll work (and do no harm if it doesn't).

### CODE REVIEW

**Comment by filbo** [comment]
This finally showed up for me, and I was able to test it by pasting just the entry into the debug box and using my 'Merge Custom & Standard Hideables' option; and it works fine.

**Comment by filbo** [comment]
argh

**Comment by matt-kruse** [comment]
Why so testy, @filbo ? Life is really busy for me. I miss some things. I'm exhausted. Doing my best...

**Comment by filbo** [comment]
I have a great deal of built-up frustration about trying to commit various things to SFx and having them ignored for long periods of time.  This one, I really had poked you several different ways (commenting here, posting directly to your attention on FB as well as 'invoking' you on FB comments about the issue) -- and at the same time we've had something like 8 different user posts complaining about 'local products in marketplace'.

Intellectually I know there are various mitigations (a big one being that FB notifications are @(%&@#% utterly screwed up right now, so I really have no evidence that you saw any of my attempts through that channel).  Unfortunately, 'knowing' something like that doesn't help much with the emotional response.

**Comment by filbo** [comment]
... I acknowledge that I was unnecessarily testy.  Sorry.

**Pull request merged**
