### PR TITLE
filters.json: polishing / update of 1 '[US] Election/Politics 2019'

### PR DESCRIPTION
**Pull request by filbo**
Change title to reflect actual purpose:

- Election/Politics 2019 => US Election/Politics 2019

Remove first names whose last names are sufficiently unique:

- amy klobuchar => klobuchar
- eric swalwell => swalwell
- jay inslee => inslee
- john hickenlooper => hickenlooper
- kirsten gillibrand => gillibrand

Split whose both names are sufficiently unique:

- tulsi gabbard => tulsi|gabbard

Add sufficiently unique last name:

- => o'rourke

Add last name to insufficiently unique first names:

- bernie => bernie sanders
- hillary => hillary clinton

Add 2nd spellings:

- bill weld
- julián castro

Add 2 further declared + 2 highly leaning Democratic candidates:

- wayne messam (as 'messam')
- mike gravel
- michael bennet
- stacey abrams

Add one politics / flame word:

- => maga

Change for consistency:

- Mitch McConnell => mitch mcconnell

### CODE REVIEW

**Comment by filbo** [comment]
I will not merge this without review...

Aware that 'bernie => bernie sanders' and 'hillary => hillary clinton' are likely to make this moderately less effective; but those names are just too common to use in bare form.

There are probably 1000 'shrillary' 'drumph' 'demonrats' etc. trash talk words that could be added, but ... that's just too much.

**Comment by matt-kruse** [comment]
I'm fine with these changes, some I considered but didn't do yet, just seeing how things play out and what really is unique. I think 'bernie' is sufficiently unique, but I agree hillary surely isn't.
I suppose maga is fine, but I hope it doesn't accidently filter out posts about the Mexican American Grocers Association. :) 
Did you test this locally, with the special characters?

**Comment by filbo** [comment]
> Did you test this locally, with the special characters?

Um, no :)

I don't have a mechanism for fake-subscription, to fully test that there are no escaping issues etc.  But I didn't make any changes that would affect that; just the one possibly-challenging Unicode char.

Pasting the 'list|of|strings|to|match|including|julián' into the filter editor works; at least it finds lots of Trump & Bernie Sanders & a few others -- I would probably have to search for a while to find a Julián Castro mention to specifically verify that.

Oh, wait... [facebook.com/julianforthefuture](https://facebook.com/julianforthefuture), duh:
image
image

**Comment by filbo** [comment]
BTW, I would like to make some other changes to this, in the 'action' section.

1. Change the hide message to include $1 (as in my pic, but perhaps with the filter name still in it)
2. Edit the 1st action so that if the user changes it to move-to-tab, the tab name is already 'Politics'
3. Edit the 2nd 'action' entry to be move-to-tab, Politics; then hide-with-message; then change it back to blank

This preloads it with my recommended configuration, without actually cramming it onto people.  I've learned that issuing subscription filters which _by default_ create tabs is a Bad Idea.

tmp

**Comment by matt-kruse** [comment]
Tested and works fine for me, so I'm merging. I will make additional filter changes and commit a second time.

**Pull request merged**
